### ISSUE TITLE
Using CacheInterceptor on endpoint and returning classes using class-validator decorators and applying @Excluded() decorator is not excluding the attribute in the cached response.

### ISSUE THREAD

**Issue by zenstok** [nestjs/cache-manager#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When applying the CacheInterceptor on endpoints and returning classes that use class-validator decorators, the application of the `@Excluded()` decorator doesn't seem to exclude the attribute in the cached response. In the non-cached response it works as expected.

### Minimum reproduction code

https://github.com/nestjs/cache-manager

### Steps to reproduce

1. Apply cache interceptor on a route that returns an object which is an instance of a class with an `@Excluded()` decorator applied on an attribute.

```
  @UseInterceptors(CacheInterceptor)
  @CacheTTL(30000)
  @Get('/test')
  test() {
    return this.testService.getResult();
  }
  ```
  
  2. Check the initial response which should NOT return the excluded attribute, as expected. (non-cached response)
  
  3. Check the second response which should NOT return the excluded attribute, but surprisingly, the cache is not taking this into account and it also returns the excluded attribute. (cached response)
 
  
  
  

### Expected behavior

The attribute exclusion should also apply to the cached response.

### Package version

1.0.0

### NestJS version

9.4.0

### Node.js version

18.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
