### ISSUE TITLE
CacheModule.register() missing type for store property for redisStore 

### ISSUE THREAD

**Issue by NaveenAtPrima** [nestjs/cache-manager#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

As per documentation , for using the redis store with CacheModule ( exported from @nestjs/cache-manager) , we provide the value for store manually i.e. redisStore (  exported from cache-maanger-redis-store), but there's no type "Store" present in CacheMangerOptions property of CacheModule.register() method . "Store" is the property exported from 'cache-manager" in redisStore.

` CacheModule.register<RedisClientOptions>({
      store: redisStore,
      host: 'localhost', // Redis server host
      port: 6379, // Redis server port
    }),
    `
    
    Current interface for CacheMangerOptions
    
    `export interface CacheManagerOptions {
    store?: string | CacheStoreFactory | CacheStore;
    ttl?: number;
    max?: number;
    isCacheableValue?: (value: any) => boolean;
}`

### Minimum reproduction code

https://github.com/no91one/nestjs-redis.git

### Steps to reproduce

npm i
nest start --watch

### Expected behavior

export interface CacheManagerOptions {
    store?: string | CacheStoreFactory | CacheStore | Store;
    host?:string;
    port?:number;
    ttl?: number;
    max?: number;
    isCacheableValue?: (value: any) => boolean;
}

### Package version

2.1.0

### NestJS version

10.0.0

### Node.js version

18.16.1

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
