### ISSUE TITLE
Need detailed Error when set cache key.

### ISSUE THREAD

**Issue by lwyj123** [nestjs/cache-manager#231]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

![image](https://github.com/nestjs/cache-manager/assets/9214496/0d2899d0-e886-4eee-a60a-68874ed8509c)
Please expose the error detail

![image](https://github.com/nestjs/cache-manager/assets/9214496/abb58f8d-0651-4743-98c8-5a83b66dfa8c)

### Describe the solution you'd like

expose the exception detail like message.

### What is the motivation / use case for changing the behavior?

User needs to debug why the cache not works

**Comment by os-moussao** [comment]
Hello @kamilmysliwiec, would you like to review pr #242 ?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/cache-manager/pull/242
