### ISSUE TITLE
Merge injection token for cache and cache instance

### ISSUE THREAD

**Issue by snys98** [nestjs/cache-manager#253]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

for now we inject cacheManager in this way
```ts
import { CACHE_MANAGER} from '@nestjs/cache-manager';
import { Cache} from 'cache-manager';

@Controller()
export class AsyncRegisterController {
  constructor(@Inject(CACHE_MANAGER) private cacheManager: Cache) {}
```
which is hard to remember or code, because:
The `Cache` class is imported from the `cache-manager`, while `CACHE_MANAGER` token from the `@nestjs/cache-manager` package.

### Describe the solution you'd like

we can simply wrap the `Cache` from `cache-manager` with 
- cache.constants.ts
```ts
import { Cache } from "cache-manager";

export type NestCache = Cache;
export const CACHE_MANAGER = 'CACHE_MANAGER';
export const NestCache = CACHE_MANAGER;
```
this solution is not following correct structure, just to demonstrate my idea

### Teachability, documentation, adoption, migration strategy

existing code will not be affected, all we need to do is to update documentation and mark CACHE_MANAGER as deprecated?

### What is the motivation / use case for changing the behavior?

the motivation is that we can simplify our injection code to
```ts
import { NestCache } from '@nestjs/cache-manager';

@Controller()
export class AsyncRegisterController {
  constructor(@Inject(NestCache) private cacheManager: NestCache) {}
```
which is much easier and cleanner

and even more, we can avoid the `@Inject(NestCache)` by make NestCache a class that implement cache-manager's `Cache`

**Comment by kamilmysliwiec** [comment]
We could fix this up by adding the extra `useExisting` provider (= thus not introducing any breaking changes)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/cache-manager/pull/256
