### ISSUE TITLE
The register method of CacheModel does not utilize the useClass specified

### ISSUE THREAD

**Issue by mmuenker** [nestjs/cache-manager#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If the "register" method options include a "useClass" property, the class will not be utilized to determine the cache manager's options.

I am not sure if this is an issue in this repository or in the @nestjs/core repository.

### Minimum reproduction code

https://github.com/mmuenker/cache-options-are-not-resolved

### Steps to reproduce

1. yarn
2. yarn start

### Expected behavior

During startup, the CacheModule.register function creates an instance of the CacheModuleOptionsLoader class, which is defined with useClass property.

### Package version

2.2.1

### NestJS version

10.3.2

### Node.js version

18.18.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

```
$ yarn start
[Nest] 665160  - 02/08/2024, 2:50:23 PM     LOG [NestFactory] Starting Nest application...
[Nest] 665160  - 02/08/2024, 2:50:23 PM     LOG [InstanceLoader] CacheModule dependencies initialized +8ms
[Nest] 665160  - 02/08/2024, 2:50:23 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 665160  - 02/08/2024, 2:50:23 PM     LOG [RoutesResolver] AppController {/}: +4ms
[Nest] 665160  - 02/08/2024, 2:50:23 PM     LOG [RouterExplorer] Mapped {/, GET} route +1ms
[Nest] 665160  - 02/08/2024, 2:50:23 PM     LOG [NestApplication] Nest application successfully started +1ms
```

**Comment by kamilmysliwiec** [comment]
Use `registerAsync` not `register`
