### ISSUE TITLE
Dynamic cache key

### ISSUE THREAD

**Issue by CSenshi** [nestjs/cache-manager#309]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Any time you want to cache key based on request you need to manually use cacheManager.

For example I have jwt token which is passed in the header and it has some value I need to use in cache key. For this I need to manually create cache object

### Describe the solution you'd like

It would be nice `@Cache` to also accept callback

Example:
```ts
@Cache((ctx: ExecutionContext) => {
  const request = ctx.switchToHttp().getRequest();
  return request.user?.groupId;
})
```

### What is the motivation / use case for changing the behavior?

Ease of use

**Comment by kamilmysliwiec** [comment]
Declare a class that inherits from `CacheInterceptor` and provides your custom `trackBy` method https://docs.nestjs.com/techniques/caching#adjust-tracking
