### ISSUE TITLE
Cache prefix

### ISSUE THREAD

**Issue by tarikhagustia** [nestjs/cache-manager#328]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently im using redis server with multiple project, when i need to clean all cache related project A for eg, it its quite hard because we can't identify which cache belong to.

### Describe the solution you'd like

it will be good if we have the cache prefix that is configurable via module for example we can set to `nestjs:*` so when we need to delete the cache, we can delete it by prefix and the other cache that is not related to a specific project is not deleted

### What is the motivation / use case for changing the behavior?

same as the solution

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the cache-manager repository

**Comment by tarikhagustia** [comment]
@kamilmysliwiec sorry, which repository?
