### ISSUE TITLE
registerAsync + global does not work

### ISSUE THREAD

**Issue by JacobSiegle** [nestjs/cache-manager#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The modules providers are not found even though the module is specified as global.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-j7sze2?file=src%2Fapp.module.ts&terminal=start

### Steps to reproduce

Stackblitz -
Error: Nest can't resolve dependencies of the SubService (?). Please make sure that the argument "CACHE_MANAGER" at index [0] is available in the SubModule context.

Potential solutions:
- Is SubModule a valid NestJS module?
- If "CACHE_MANAGER" is a provider, is it part of the current SubModule?
- If "CACHE_MANAGER" is exported from a separate @Module, is that module imported within SubModule?
  @Module({
    imports: [ /* the Module containing "CACHE_MANAGER" */ ]
  })

### Expected behavior

The modules providers work like register

### Package version

2.2.1

### NestJS version

10.3.1

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
![image](https://github.com/nestjs/cache-manager/assets/23244943/36911b38-f948-4969-befb-63c1bc998db0)

**Comment by JacobSiegle** [comment]
@kamilmysliwiec Thanks!

useFactory?: (...args: any[]) => Promise<CacheModuleOptions<StoreConfig>> | CacheModuleOptions<StoreConfig>;

CacheModuleOptions has isGlobal when using registerAsync, I noticed you closed but do you think the type is worth fixing?

**Comment by kamilmysliwiec** [comment]
Oh yeah it is! Would you like to create a PR?
