### ISSUE TITLE
enableVersioning

### ISSUE THREAD

**Issue by Zarinia** [nestjs/cache-manager#359]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

How can use cahce with enableVersioning?
When I have a version that I know the value of the controller version with the header, it doesn't work properly because of the cache

### Minimum reproduction code

-

### Expected behavior

work with enable versioning

### Package version

2.2.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
