### ISSUE TITLE
`cache-manager 5.6.0` fails to load

### ISSUE THREAD

**Issue by flovouin** [nestjs/cache-manager#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The issue can actually be observed in #407, which tries to update to `cache-manager v5.6.0`. See this [CI step](https://app.circleci.com/pipelines/github/nestjs/cache-manager/989/workflows/91eec3e6-6e54-4d28-a2cf-762591ad0818/jobs/1868?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary).

Not only it'd be great to be able to use `cache-manager`'s latest version, but also `@nestjs/cache-manager` currently depends on [version <= 5](https://github.com/nestjs/cache-manager/blob/932d0543346139f10250e5068f040b7d08475a90/package.json#L53), which breaks with `5.6.0`.

### Minimum reproduction code

https://github.com/nestjs/cache-manager/pull/407

### Expected behavior

Depending on `cache-manager v5.6.0` does not raise an error.

### Package version

2.2.2

### NestJS version

10

### Node.js version

20

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by MikhaelGerbet** [comment]
i confirm, the 5.5.3 return this error : 

`The "cache-manager" package is missing. Please, make sure to install this library ($ npm install cache-manager) to take advantage of CacheModule.`

But ! The `5.6.1` published 2 hours ago works or with the previous requirement `5.5.3`

**Comment by MikhaelGerbet** [comment]
perhaps fixed on this [PR](https://github.com/nestjs/cache-manager/pull/409)
