### ISSUE TITLE
Support refresh cache keys in background feature of cache-manager

### ISSUE THREAD

**Issue by windybirth** [nestjs/cache-manager#474]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When use refresh cache keys in background feature of cache-manager,  `refreshThreshold` and `onBackgroundRefreshError` is not defined.

### Describe the solution you'd like

I want to use the  `refreshThreshold` and `onBackgroundRefreshError` option in nestjs@cache-manager, but it is not defined in [CacheManagerOptions](https://github.com/nestjs/cache-manager/blob/634a89dce78565ea6a6e94aa38fa6091f4a4b4ec/lib/interfaces/cache-manager.interface.ts#L67).

### What is the motivation / use case for changing the behavior?

When I use nestjs@cache-manager I want to use the  `refreshThreshold` and `onBackgroundRefreshError` option in the cache manager.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/cache-manager/pull/475
