### ISSUE TITLE
Outdated Redis Cache examples

### ISSUE THREAD

**Issue by karlismelderis-mckinsey** [nestjs/cache-manager#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Please replace `cache-manager-redis-store` with `cache-manager-redis-yet`

https://docs.nestjs.com/techniques/caching#different-stores
https://github.com/nestjs/cache-manager/blob/master/package.json#L34C6-L34C31

`cache-manager-redis-store` is old, doesn't feel to be maintained and has a bug that probably won't get fixed:
https://github.com/nestjs/cache-manager/issues/74

it's better to use cache-manager official Redis store in your examples and dependencies

### Minimum reproduction code

N/A

### Expected behavior

Docs and cache library dependencies updated

### Package version

2.2.2

### NestJS version

9.x

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by karlismelderis-mckinsey** [comment]
Also you will be able to remove warning from the docs as `cache-manager-redis-yet` uses redis v4 package

**Comment by arketec** [comment]
Also, cache-manager no longer exports Cache interface as of v6

although this project's peerDependencies state <=5, so not sure that was updated as well

**Comment by xavierraffin** [comment]
@arketec I created a ticket specifically on that problem: https://github.com/nestjs/cache-manager/issues/516

**Comment by kamilmysliwiec** [comment]
Fixed
