### ISSUE TITLE
cache manager is not working correctly

### ISSUE THREAD

**Issue by zhalil** [nestjs/cache-manager#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

hello, when i register :
```typescript
export const RedisConfig: CacheModuleAsyncOptions = {
    isGlobal: true,
    imports: [ConfigModule],
    useFactory: async (configService: ConfigService) => {
        const store = await redisStore({
            socket: {
                host: configService.get<string>('REDIS_HOST'),
                port: parseInt(configService.get<string>('REDIS_PORT')!),
            },
        });
        return {
            store: store,
            ttl: configService.get('CACHE_TTL'),
        };
    },
    inject: [ConfigService],
};

CacheModule.registerAsync(RedisConfig)
```
field ttl and max not working and always -1 ttl in redis
if i use 
```typescript
    @CacheTTL(1000) 
    //or
    this.cacheManager.set("zxc",'qwe',1000);
```

its not working and in redis always -1 ttl

but if i use 
```typescript
@CacheTTL({
        // @ts-ignore
        ttl:1000
    })
    
    //or
    
     // @ts-ignore
        this.cacheManager.set("zxc",'qwe',{
            ttl:1000
        });
```
its working, but the documentation states that you just need to pass a number and not an object, the default ttl and max still won’t work from config, if i use default register 
```typescript
CacheModule.register(CacheConfig)
```
ttl and max from config working, but the rest works the same
```typescript
@CacheTTL({
        // @ts-ignore
        ttl:1000
    })
    
    //or
    
     // @ts-ignore
        this.cacheManager.set("zxc",'qwe',{
            ttl:1000
        });
```

### Minimum reproduction code

https://github.com/zhalil/cachenestbug

### Expected behavior

```typescript
    @CacheTTL(1000)
    //or
    this.cacheManager.set("zxc",'qwe', 1000);
```
and ttl and max from config working in async register

### Package version

^2.3.0

### NestJS version

^10.0.0

### Node.js version

22.9.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
This depends on what cache-manager version you use. Docs show examples for v5, while you're very likely using v4 in your project

**Comment by zhalil** [comment]
> This depends on what cache-manager version you use. Docs show examples for v5, while you're very likely using v4 in your project

project deps: 
```
  "dependencies": {
    "@nestjs/cache-manager": "^2.3.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.3.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "cache-manager": "^5.7.6",
    "cache-manager-redis-store": "^3.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },
```
