### ISSUE TITLE
Support cache-manager v6

### ISSUE THREAD

**Issue by MickL** [nestjs/cache-manager#551]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

- cache-manager v6 has moved to [Keyv](https://keyv.org/)
- Docs need to be updated (dont use cache-manager-redis-yet)

**Comment by carry0987** [comment]
@MickL In the current package.json, cache-manager has been updated to v6. Perhaps the author plans to release the next update?
