### ISSUE TITLE
Cache TTL not working correctly

### ISSUE THREAD

**Issue by gerardvc** [nestjs/cache-manager#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I had integrated the Cache Manager for my NestJS App with an external Redis Cluster.Whenever I try to set any data using the cache manager it always sets the ttl as -1 which means that the key never expires from Redis,This happens despite specifying the ttl as per the documentation.This package seems to work with an older version of the cache-manager like 4.0.0.

```

import { CACHE_MANAGER } from '@nestjs/cache-manager';
import { Cache } from 'cache-manager';


@Injectable()
export class AppService {
  private readonly logger = new Logger(AppService.name);

  constructor(,
    @Inject(CACHE_MANAGER) private readonly cacheManager: Cache,
  ) {

  async serverStatus(): Promise<Object> {
    try {

        // Was using the below command to set the cached value
        `await this.cacheManager.set('Data', 'Test', 3000);`
        
        // Was using the below command to get the cached value
        `const cachedValue = await this.cacheManager.get('Data');`

    } catch (error) {
      throw new InternalServerErrorException(error.message, error.status);
    }


```

### Minimum reproduction code

NA

### Expected behavior

The ttl should be set as defined and the key should expire.

### Package version

2.3.0

### NestJS version

10.4.1

### Node.js version

20.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

cache-manager: v5.7.6

**Comment by MBach** [comment]
I have the same issue with TTL too. The following snippet isn't working:

```ts
        CacheModule.register({
            useFactory: async (config: ConfigService) => {
                const store = await redisStore({
                    socket: {
                        host: config.get("REDIS_HOST"),
                        port: config.get("REDIS_PORT")
                    },
                    username: config.get("REDIS_USERNAME"),
                    password: config.get("REDIS_PASSWORD"),
                    name: "my-client"
                })
                return {
                    store: store as unknown as CacheStore,
                    ttl: 24 * 60 * 60_000 // 24h - TODO: doesn't work
                }
            }
        })
```
