### ISSUE TITLE
Access to cache manager underlying client

### ISSUE THREAD

**Issue by DavideCarvalho** [nestjs/cache-manager#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Until cache-manager version 5.7.6, we could access the underlying client store with `this.cacheManager.store`, but after cache-manager version 6, they don't have it anymore

[From their issue here](https://github.com/jaredwray/cacheable/issues/902#issuecomment-2495551729) they created a `getClient` function on @keyv/redis to give this same functionality

So if I upgrade cache-manager to version 6, I cannot do this anymore

```ts
const keys = await this.cacheManager.store.keys(`*${baseId}*`); // Error because cacheManager doesn't have .store anymore
for (const key of keys) {
  await this.cacheManager.del(key);
}
```

### Minimum reproduction code

none

### Expected behavior

I should have `.store` function or any other function that gives me the same thing as the previous `.store` had

### Package version

2.3.0

### NestJS version

10.4.15

### Node.js version

v23.4.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Not sure how is this relevant to `@nestjs/cache-manager`(?)

**Comment by DavideCarvalho** [comment]
Ty for replying!

Isn't `@nestjs/cache-manager` a wrapper that has `@keyv/redis` as a dependency? We as nestjs users don't have access to `@keyv/redis` - at least, I couldn't find how to get access to underlying `@keyv/redis` to try to use this `.getClient` function

So, if we cannot get the underlying cache store from the `.store` property from `cache-manager` anymore, but we can get it from `@keyv/redis`, and `@nestjs/cache-manager` has `@keyv/redis` as a dependency, I believe it should have a way to expose `.getClient` from `@keyv/redis`

Am I wrong? wdyt?

Ty for your reply!

**Comment by micalevisk** [comment]
@DavideCarvalho > Isn't `@nestjs/cache-manager` a wrapper that has `@keyv/redis` as a dependency

no. `@nestjs/cache-manager` has no hard dependencies, as you can see by running `npm view @nestjs/cache-manager dependencies`

**Comment by kamilmysliwiec** [comment]
+ if you want the Keyv/redis instance to be accessible/injectable, just register it as a provider, inject it into the cache module options factory, and pass it down as a "store" property instead of creating the instance inline

**Comment by cherviakovtaskworld** [comment]
Answer is here: https://github.com/jaredwray/cacheable/issues/902
