### ISSUE TITLE
Keyv as store behave different than KeyvRedis

### ISSUE THREAD

**Issue by zhuxb711** [nestjs/cache-manager#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

for unknown reason, in some situation, I could not found any key-value pair in redis after caching.
I think this issue only presents if I assign the field 'stores' with **Keyv** instead of **KeyvRedis**

#### Found key-value pair in redis:
```typescript
CacheModule.registerAsync({
      isGlobal: true,
      useFactory: () => {
        return {
          stores: [new KeyvRedis(<cluster or url>)],
          namespace: 'my-namespace'
        };
      }
    })
```

#### Not found any key-value pair in redis:
```typescript
CacheModule.registerAsync({
      isGlobal: true,
      useFactory: () => {
        return {
          stores: [
            new Keyv({
              useKeyPrefix: false,
              namespace: 'my-namespace',
              store: new KeyvRedis(<cluster or url>, {
                keyPrefixSeparator: ':'
              })
            })
          ]
        };
      }
    })
```

### Minimum reproduction code

<None>

### Expected behavior

Keyv should work the same as KeyvRedis

### Package version

3.0.0-next.0

### NestJS version

10.4.15

### Node.js version

22.11.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by zhuxb711** [comment]
However, for the situation that "**could not found key-value pair in redis**", I could still write and read data as normal. I suspect that @nestjs/cache-manage using the memory-cache rather than redis

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

You can also refer to this file to see how we set up cache providers https://github.dev/nestjs/cache-manager/blob/2ed16e1b878330e5474797e36253cba201bd613a/lib/cache.providers.ts#L14

**Comment by zhuxb711** [comment]
Double checked and found that is a false issue
