### ISSUE TITLE
Set `ttl` via `this.cacheManager.set` is not working when `ttl` is set in `CacheModule.registerAsync` as global

### ISSUE THREAD

**Issue by diandian18** [nestjs/cache-manager#74]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

Set `ttl` via `this.cacheManager.set` is not working when `ttl` is set in `CacheModule.registerAsync` as global. `ttl` is always set as the global value.

### Minimum reproduction code

https://github.com/nestjs/cache-manager

### Steps to reproduce

1. `ttl` set to `100` in `CacheModule.registerAsync` as global:

```typescript
import { redisStore } from 'cache-manager-redis-store';

CacheModule.registerAsync<RedisClientOptions>({
  isGlobal: true,
  inject: [ConfigService],
  useFactory: async (configService: ConfigService) => ({
    store: redisStore,
    url: configService.get('REDIS_URL'),
    password: configService.get('REDIS_PASS'),
    ttl: 100,
  }),
}),
```

3. `ttl` set to `200` in `xx.service.ts`:

```typescript
this.cacheManager.set(
  'key',
  'value',
  200,
)
```

### Expected behavior

Check in redis client tool, `TTL` is `200`

### Package version

1.0.0

### NestJS version

9.0.0

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
`cacheManager` is just a wrapper around `cacheManager.caching()` instance. I'd suggest reporting this issue here https://github.com/node-cache-manager/node-cache-manager instead
