### ISSUE TITLE
Customize CacheKey according to request parameters

### ISSUE THREAD

**Issue by xiaoqiang1999** [nestjs/cache-manager#80]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When I have a method like this, I can't set the cache key using id:
![image](https://github.com/nestjs/cache-manager/assets/40377409/72d31618-fa2e-4b77-af77-fe449ba253d6)

### Describe the solution you'd like

Similarly, customize the CacheKey:
![image](https://github.com/nestjs/cache-manager/assets/40377409/0a4639a4-3c4a-4d18-8dc1-171bb35f14c2)

Or so:
![image](https://github.com/nestjs/cache-manager/assets/40377409/399ab260-391a-4c16-8c7a-bf123e8e9c56)

### What is the motivation / use case for changing the behavior?

![image](https://github.com/nestjs/cache-manager/assets/40377409/72d31618-fa2e-4b77-af77-fe449ba253d6)

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/caching#adjust-tracking
